### PR TITLE
Link hints

### PR DESCRIPTION
**Pull request by Ralt**

### CODE REVIEW

**Comment by Ralt** [comment]
Do you need me to clean up git history?

**Comment by Ralt** [comment]
A good improvement would be moving the `(eval-in-page-js browser *link-hints-ps*)` call to an on-new-tab hook.

**Comment by AeroNotix** [comment]
@Ralt git history is fine. Could you provide some screenshots, please?

**Comment by Ralt** [comment]
Sure.

When running the link hints: http://i.imgur.com/g0hyIb5.png
When hitting "B": http://i.imgur.com/NWKthnh.png

**Comment by AeroNotix** [comment]
Amazing work.

**Pull request merged**
